config/routes.rb
Analytics::Application.routes.draw do
  resources :cohorts

  resources :jobs, :only => [:index, :show]
  resources :segment_definitions

  match "page_views/page_data/:id" => "page_views#page_data", :as => :page_data, :via => [:get, :post, :put]
  resources :page_views, :only => [:index]
  
  match "standard_events/event_data/:id" => "standard_events#event_data", :as => :event_data, :via => [:get, :post, :put]
  match "standard_events/event_summary" => "standard_events#event_summary", :as => :event_summary, :via => [:get, :post, :put]
  resources :standard_events, :only => [:index, :show]

  match "identites/summary" => "identities#summary", :as => :identities_summary, :via => [:get, :post]
  match "identities/by_segment/:id" => "identities#by_segment", :as => :identities_by_segment, :via => [:get]
  resources :identities, :only => [:index, :show]
  
  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  match "events/create" => "events#create", :via => [:get, :post, :put]
  resources :events, :only => [:index, :create, :show]
end

app/models/segment_definition.rb
class SegmentDefinition < ActiveRecord::Base
  belongs_to :user
  has_many :identity_segments
  has_many :identities, :through => :identity_segments

  has_many :segment_events

  def member_session_ids
    # this is where intersection will be done in the future
    event_names = self.segment_events.collect{|se| se.event_name }
    event_names.collect do |event_name|
      StandardEvent.select('DISTINCT session_id').where(:name => event_name).pluck(:session_id)
    end.flatten.uniq
  end

  def member_identities
    sessions = Session.where(:id => self.member_session_ids)
    sessions.collect{|s| s.identity}.uniq.select{|i| !i.nil?}
  end

  def members
    self.identities
  end

  def members_on_week(week)
    self.identities.joins(:identity_segments).where('identity_segments.left_at IS NULL').where('identity_segments.entered_at > ? AND identity_segments.entered_at < ?', week.beginning_of_week, week.end_of_week)
  end

  def recompute!
    result = Benchmark.measure do
      self.member_identities.each do |identity|
        id_seg = IdentitySegment.where(:segment_definition_id => self.id).where(:left_at => nil).where(:identity_id => identity.id).first_or_initialize
        if id_seg.entered_at.nil?
          id_seg.entered_at = identity.first_event_timestamp(self.segment_events.collect{|s| s.event_name}).timestamp
        end
        id_seg.save!
      end

      self.member_count = member_identities.count
      self.save!
    end
    self.compute_seconds = result.real
    self.save!
  end

  def enqueue_recompute
    self.delay.recompute!
  end

  def self.items_for_select
    SegmentDefinition.all.collect {|s| [s.name, s.id]}
  end
end

app/controllers/segment_definitions_controller.rb
class SegmentDefinitionsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    authorize! :read, SegmentDefinition, :message => 'Not authorized as an administrator.'
    @segment_defs = SegmentDefinition.all
  end

  def new
    authorize! :manage, SegmentDefinition, :message => 'Not authorized as an administrator.'
    @segment_def = SegmentDefinition.new
  end

  def create
    authorize! :manage, SegmentDefinition, :message => 'Not authorized as an administrator.'
    @segment_def = SegmentDefinition.new
    @segment_def.name = segment_definition_params[:name]
    @segment_def.user_id = current_user.id
    if @segment_def.save
      begin
        event_names = segment_definition_params[:event_name]
        event_names.each do |name|
          if name.present? && name != ""
            SegmentEvent.where(:segment_definition_id => @segment_def.id).where(:event_name => name).first_or_create
          end
        end
      rescue Exception => e
        flash[:error] = "There were some errors"
        redirect_to :back
        return
      end
      flash[:success] = "Saved."
      @segment_def.enqueue_recompute
      redirect_to segment_definitions_path
    end
  end

  def show
    authorize! :read, SegmentDefinition, :message => 'Not authorized as an administrator.'
    @segment_def = SegmentDefinition.find params[:id]
    @segment_member_identities = @segment_def.identity_segments.order('entered_at DESC').page(params[:page]).per_page(25)
  end

  private

  def segment_definition_params
    params.require(:segment_definition).permit!
  end
end

app/helpers/segment_definitions_helper.rb
module SegmentDefinitionsHelper
end

app/views/segment_definitions/index.html.haml
%ol.breadcrumb
  %li.active Segments

.span8
  .panel.panel-default
    .panel-heading
      = link_to "Create segment", new_segment_definition_path, :class => "btn btn-primary btn-sm"
      = @segment_defs.count
      segments
    .panel-body
    %ul.list-group
      - @segment_defs.each do |segment_def|
        %a{:href => segment_definition_path(segment_def), :class => "list-group-item"}
          = segment_def.name
          %span.label.label-primary
            = segment_def.member_count
            identities
          %span.label.label-info.pull-right
            - if segment_def.updated_at == segment_def.created_at
              processing
            - else
              == last activity: #{time_ago_in_words(segment_def.updated_at)} ago

app/views/segment_definitions/new.html.haml
%ol.breadcrumb
  %li= link_to "Segments", segment_definitions_path
  %li.active New

= form_for @segment_def do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :event_name, "Users who have performed the event"
  = f.select :event_name, StandardEvent.items_for_select, {}, {:multiple => true, :size => 25}
  = f.submit

app/views/segment_definitions/show.html.haml
%ol.breadcrumb
  %li= link_to "Segments", segment_definitions_path
  %li.active= @segment_def.name

.span8
  .panel.panel-default
    .panel-heading
      %p 
        Segment:
        %b= @segment_def.name
        == (#{@segment_member_identities.count})
      %p
        Any of the following events:
        - @segment_def.segment_events.each do |segment_event|
          .span.label.label-primary=segment_event.event_name
      %p
        Compute time:
        - if @segment_def.compute_seconds
          = distance_of_time_in_words(@segment_def.compute_seconds)
        - else
          (unknown)
    .panel-body
      %h3 Daily new members
      = line_chart @segment_def.members.group_by_day(:entered_at).count
  .panel.panel-default
    .panel-heading
      Members
    .panel-body
      %table.table
        %tr
          %th ID
          %th Email
          %th Entered Segment
        - @segment_member_identities.each do |id_seg|
          %tr
            %td
              = id_seg.identity.id
            %td
              = link_to id_seg.identity.email, identity_path(id_seg.identity)
            %td{:title => id_seg.entered_at}
              = time_ago_in_words(id_seg.entered_at) 
              ago
      = will_paginate @segment_member_identities


  