config/routes.rb
Analytics::Application.routes.draw do
  resources :cohorts

  resources :jobs, :only => [:index, :show]
  resources :segment_definitions

  match "page_views/page_data/:id" => "page_views#page_data", :as => :page_data, :via => [:get, :post, :put]
  resources :page_views, :only => [:index]
  
  match "standard_events/event_data/:id" => "standard_events#event_data", :as => :event_data, :via => [:get, :post, :put]
  match "standard_events/event_summary" => "standard_events#event_summary", :as => :event_summary, :via => [:get, :post, :put]
  resources :standard_events, :only => [:index, :show]

  match "identites/summary" => "identities#summary", :as => :identities_summary, :via => [:get, :post]
  match "identities/by_segment/:id" => "identities#by_segment", :as => :identities_by_segment, :via => [:get]
  resources :identities, :only => [:index, :show]
  
  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  match "events/create" => "events#create", :via => [:get, :post, :put]
  resources :events, :only => [:index, :create, :show]
end

app/models/standard_event.rb
class StandardEvent < ActiveRecord::Base
  belongs_to :event
  belongs_to :session
  
  def self.create_from_event!(event)
    event_id = event.id
    if StandardEvent.find_by_event_id(event_id).nil? # has this event already been created?
      name = event.to_json['event']
      timestamp = event.to_json['timestamp']
      unique_session_id = event.to_json['sessionId']
      session = Session.where(:unique_id => unique_session_id).first_or_create
      se = StandardEvent.create!(:name => name, :timestamp => timestamp, :event_id => event_id, :session_id => session.id)
      return se
    end
  end

  def reextract!
    self.name = self.event.to_json['event']
    self.timestamp = self.event.to_json['timestamp']
    self.session_id = self.event.to_json['sessionId']
    self.save!
  end

  def to_param
    self.name
  end

  def self.items_for_select
    StandardEvent.select('DISTINCT name').collect {|e| e.name}
  end
end

app/controllers/standard_events_controller.rb
class StandardEventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, StandardEvent, :message => 'Not authorized as an administrator.'
    @standard_events = StandardEvent.select('DISTINCT name')
  end

  def show
    authorize! :read, StandardEvent, :message => 'Not authorized as an administrator.'
    @standard_event_name = params[:id]
  end

  def event_data
    authorize! :read, StandardEvent, :message => 'Not authorized as an administrator.'
    @fact = params[:id]
    @klass = StandardEvent
    render json: retrieve_fact_by_dimensions # in application_controller.rb
  end

  def event_summary
    authorize! :read, StandardEvent, :message => 'Not authorized as an administrator.'
    @standard_events = StandardEvent.select('DISTINCT name')
    @data = @standard_events.map do |e|
      @fact = e.name
      @klass = StandardEvent
      {name: e.name, data: retrieve_fact_by_dimensions}
    end
    render json: @data
  end
end

app/helpers/standard_events_helper.rb
module StandardEventsHelper
end

app/views/standard_events/index.html.haml
%ol.breadcrumb
  %li.active Events
.span8
  .panel.panel-default
    .panel-heading
      Events Overview (last 30 days)
    .panel-body
      = line_chart event_summary_path
    %ul.list-group
      - @standard_events.each do |event|
        = link_to event.name, standard_event_path(event), :class => "list-group-item"

app/views/standard_events/show.html.haml
%ol.breadcrumb
  %li= link_to "Events", standard_events_path
  %li= @standard_event_name
.span8
  .panel.panel-default
    .panel-heading
      = render "layouts/view_prefs"
    .panel-body
      #chart

:javascript
  window.Prefs = {
    time_bucket: "daily",
    last: 30,
    chart_type: "line",
    data_url: "/standard_events/event_data",
    fact: "#{@standard_event_name}"
  };

  reloadCharts();