config/routes.rb
Analytics::Application.routes.draw do
  resources :cohorts

  resources :jobs, :only => [:index, :show]
  resources :segment_definitions

  match "page_views/page_data/:id" => "page_views#page_data", :as => :page_data, :via => [:get, :post, :put]
  resources :page_views, :only => [:index]
  
  match "standard_events/event_data/:id" => "standard_events#event_data", :as => :event_data, :via => [:get, :post, :put]
  match "standard_events/event_summary" => "standard_events#event_summary", :as => :event_summary, :via => [:get, :post, :put]
  resources :standard_events, :only => [:index, :show]

  match "identites/summary" => "identities#summary", :as => :identities_summary, :via => [:get, :post]
  match "identities/by_segment/:id" => "identities#by_segment", :as => :identities_by_segment, :via => [:get]
  resources :identities, :only => [:index, :show]
  
  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  match "events/create" => "events#create", :via => [:get, :post, :put]
  resources :events, :only => [:index, :create, :show]
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  has_many :sessions
  has_many :identity_segments
  has_many :segment_definitions, :through => :identity_segments

  def self.create_from_event!(event)
    identity = Identity.new
    identity.userid = event.to_json['userId']
    identity.email = event.to_json['traits']['email']
    identity.username = event.to_json['traits']['email']
    identity.created = event.to_json['traits']['created']
    identity.save!
    identity
  end

  def session_ids_as_strings
    self.sessions.pluck(:id).collect{|i| i.to_s}
  end

  def standard_events
    StandardEvent.where(:session_id => self.session_ids_as_strings).order('timestamp DESC')
  end

  def first_event_timestamp(event_names)
    event_names.collect do |event_name|
      StandardEvent.where(:name => event_name).where(:session_id => self.session_ids_as_strings).order('timestamp ASC').first
    end.compact.sort {|a, b| a.timestamp <=> b.timestamp}.first
  end

  def first_visit_string
    sessions = self.session_ids_as_strings.collect {|s| Session.find(s.to_i).unique_id }
    visit = Event.where("properties->'action' = 'Page'").where("properties->'sessionId' IN (?)", sessions.join(",")).order("properties->'timestamp'").first
    if visit.nil?
      "no visits"
    else
      visit.source_string
    end
  end
end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, Identity, :message => 'Not authorized as an administrator.'
  end

  def summary
    authorize! :read, Identity, :message => 'Not authorized as an administrator.'
    render json: Identity.group_by_week(:created, :last => 12, :format => "%m/%d/%Y").count
  end

  def show
    @identity = Identity.find params[:id]
  end

  def by_segment
    @segment_def = SegmentDefinition.find params[:id]
  end
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/by_segment.html.haml
%ol.breadcrumb
  %li= link_to "Identities", identities_path
  %li.active== Identities by segment: #{@segment_def.name}

.span8
  .panel
    .panel-heading
      %h2
        Identities by segment:
        = @segment_def.name
    .panel-body
      %table.table
        %tr
          %th Identity
          %th First Event
          %th src / med / camp
          %th Date
        - @segment_def.identity_segments.each do |seg_id|
          %tr
            %td= link_to seg_id.identity.email, identity_path(seg_id.identity)
            %td= seg_id.first_event
            %td= seg_id.identity.first_visit_string
            %td= seg_id.entered_at.strftime("%m/%d/%Y")

app/views/identities/index.html.haml
%h1
  = Identity.count
  identities

= column_chart identities_summary_path

%h3 View identities by segment:
%ul
  - SegmentDefinition.all.each do |seg_def|
    //%li= link_to seg_def.name, identities_by_segment_path(seg_def)
    %li= seg_def.name

app/views/identities/show.html.haml
%ol.breadcrumb
  %li= link_to "Identities", identities_path
  %li.active= @identity.email

.span8
  .panel.panel-default
    .panel-heading
      = image_tag(avatar_url(@identity.email), :class => "img-thumbnail")
      = @identity.email
      events (newest first)
    .panel-body
      %h3 Segments:
      - @identity.segment_definitions.each do |seg|
        = link_to seg.name, segment_definition_path(seg), :class => "btn btn-sm btn-primary"
      %h3 Activity
      %table.table
        %tr
          %th ID
          %th name
          %th when
          %th timestamp
        - @identity.standard_events.each do |se|
          %tr
            %td= se.id
            %td= se.name
            %td== #{time_ago_in_words(se.timestamp)} ago
            %td= se.timestamp